name: actonic_adboard
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  rxdart: ^0.27.7
  bloc: ^8.1.2
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12
  image_picker: ^1.0.1
  sqflite: ^2.3.0
  path_provider: ^2.0.15
  provider: ^6.0.5
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/images/nophoto.jpg
  uses-material-design: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
